USE [master]

/****** Object:  Database SitMescriptcreated    Script Date: 26.08.2020 23:17:45 ******/
CREATE DATABASE SitMeScriptCreated
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'SitMeScriptCreated', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\SitMeScriptCreated.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'SitMeScriptCreated_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\SitMeScriptCreated_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT


ALTER DATABASE SitMescriptcreated SET ANSI_NULL_DEFAULT OFF 
ALTER DATABASE SitMescriptcreated SET ANSI_NULLS OFF 
ALTER DATABASE SitMescriptcreated SET ANSI_PADDING OFF 
ALTER DATABASE SitMescriptcreated SET ANSI_WARNINGS OFF 
ALTER DATABASE SitMescriptcreated SET ARITHABORT OFF 
ALTER DATABASE SitMescriptcreated SET AUTO_CLOSE OFF 
ALTER DATABASE SitMescriptcreated SET AUTO_SHRINK OFF 
ALTER DATABASE SitMescriptcreated SET AUTO_UPDATE_STATISTICS ON 
ALTER DATABASE SitMescriptcreated SET CURSOR_CLOSE_ON_COMMIT OFF 
ALTER DATABASE SitMescriptcreated SET CURSOR_DEFAULT  GLOBAL 
ALTER DATABASE SitMescriptcreated SET CONCAT_NULL_YIELDS_NULL OFF 
ALTER DATABASE SitMescriptcreated SET NUMERIC_ROUNDABORT OFF 
ALTER DATABASE SitMescriptcreated SET QUOTED_IDENTIFIER OFF 
ALTER DATABASE SitMescriptcreated SET RECURSIVE_TRIGGERS OFF 
ALTER DATABASE SitMescriptcreated SET  DISABLE_BROKER 
ALTER DATABASE SitMescriptcreated SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
ALTER DATABASE SitMescriptcreated SET DATE_CORRELATION_OPTIMIZATION OFF 
ALTER DATABASE SitMescriptcreated SET TRUSTWORTHY OFF 
ALTER DATABASE SitMescriptcreated SET ALLOW_SNAPSHOT_ISOLATION OFF 
ALTER DATABASE SitMescriptcreated SET PARAMETERIZATION SIMPLE 
ALTER DATABASE SitMescriptcreated SET READ_COMMITTED_SNAPSHOT OFF 
ALTER DATABASE SitMescriptcreated SET HONOR_BROKER_PRIORITY OFF 
ALTER DATABASE SitMescriptcreated SET RECOVERY SIMPLE 
ALTER DATABASE SitMescriptcreated SET  MULTI_USER 
ALTER DATABASE SitMescriptcreated SET PAGE_VERIFY CHECKSUM  
ALTER DATABASE SitMescriptcreated SET DB_CHAINING OFF 
ALTER DATABASE SitMescriptcreated SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
ALTER DATABASE SitMescriptcreated SET TARGET_RECOVERY_TIME = 60 SECONDS 
ALTER DATABASE SitMescriptcreated SET DELAYED_DURABILITY = DISABLED 
ALTER DATABASE SitMescriptcreated SET QUERY_STORE = OFF
ALTER DATABASE SitMescriptcreated SET  READ_WRITE 